### ISSUE TITLE
No sound from Suda Music

### ISSUE THREAD

**Issue by Crilum** [Raspberry-Pi-Reviews/Suda-Music#1]
I just installed Suda Music from your install script, and there is no sound. 
I also can't tell if there is actually something playing, so maybe you could add some sort of a status to show what is playing?

Terminal output:
```
=====================================
Please wait while Suda Music Starts
=====================================
                                     
=====================================
Suda Music has started
=====================================
                                     
=====================================
Enjoy your experience with Suda Music
=====================================
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html

```

**Comment by Raspberry-Pi-Reviews** [comment]
Hello, sorry I haven't been on git-hub in a while, did you wait until the GUI loaded? There is a GUI that is supposed to appear 2-10 seconds after the statement "Enjoy your experience with Suda-Music"

**Comment by Crilum** [comment]
Yes, I did wait. I loaded an MP3, and hit `Play`. It did not output any sound. I tried pressing `Volume Up`, and made sure my Volume was up, but it still did not play. Is there a missing dependency/python library that one would need?

**Comment by Raspberry-Pi-Reviews** [comment]
I will look into this problem, is there an email address that you can sends me so we can talk one on one?

**Comment by Crilum** [comment]
I'd rather not, could we just talk in this Issue?

**Comment by Raspberry-Pi-Reviews** [comment]
ok yeah this is fine, ill get back with you in about 5 to 10 minutes

**Comment by Raspberry-Pi-Reviews** [comment]
Ok, its doing the same thing with me, im gonna try and delete it and re-install it

**Comment by Raspberry-Pi-Reviews** [comment]
I do have one question, what raspberry pi are you using, if your using one

**Comment by Raspberry-Pi-Reviews** [comment]
I will continue to look at this problem.

**Comment by Crilum** [comment]
Rpi 4 4G, I'll try it in thonny

**Comment by Raspberry-Pi-Reviews** [comment]
ok, I will get back to you once I fix this problem, let me know if it works

**Comment by Crilum** [comment]
In Thonny I can run it and it works, but my MP3 is slowed down. I also have to press the pause button once before I can actually use it. 

The Volume buttons also cycle through volume levels, so once you get to the loudest, it goes quiet.

**Comment by Raspberry-Pi-Reviews** [comment]
yeah those are kinda broken, I still got to fix those. if you want, I will probably have the problem fixed by tonight or tomorrow.

**Comment by Crilum** [comment]
Ok. :+1: 
No pressure though, if you can't get it done for a few days.

**Comment by Raspberry-Pi-Reviews** [comment]
ok, have a great night

**Comment by Raspberry-Pi-Reviews** [comment]
If you are still up or something and you are reading this, do you know anybody who can check my code because I have been trying to figure this out for about 2-3 hours now and I cannot fix it.

**Comment by Crilum** [comment]
> If you are still up or something and you are reading this, do you know anybody who can check my code because I have been trying to figure this out for about 2-3 hours now and I cannot fix it.

Sorry, I don't know anyone who could help...
I'm a ***complete*** python beginner, so I can't help.. I wish I could.

**Comment by Raspberry-Pi-Reviews** [comment]
ok thanks, ill still try but my question is why does it work in thonny but not work when you try to use it without thonny

**Comment by Raspberry-Pi-Reviews** [comment]
I have the old code on my other computer so when this weekend (probably friday) I will get the code transfered over to this computer

**Comment by Crilum** [comment]
Found it. Don't run with sudo.
Just do:
```
python3 ${HOME}/Suda-Music/musicplayer.py
```

Don't know why it does that, but it does..

**Comment by Raspberry-Pi-Reviews** [comment]
wait does it work now?

**Comment by Crilum** [comment]
Yeah

**Comment by Raspberry-Pi-Reviews** [comment]
sweet lol thanks

**Comment by Crilum** [comment]
It's still slow, but it plays, and you don't have to click the pause button twice to get it to work..

**Comment by Raspberry-Pi-Reviews** [comment]
it plays my songs normal

**Comment by Crilum** [comment]
Huh.. I might do some googling

**Comment by Raspberry-Pi-Reviews** [comment]
im gonna try and update all the scripts in github

**Comment by Raspberry-Pi-Reviews** [comment]
and ill tell you when to delete your Suda Music folder

**Comment by Crilum** [comment]
I'm making a PR with suggested changes, and you can compare them if you want.

**Comment by Raspberry-Pi-Reviews** [comment]
ok, try it now like delete the suda music folder and re-install it

**Comment by Crilum** [comment]
```shell
$ wget -qO- https://raw.githubusercontent.com/Raspberry-Pi-Reviews/Suda-Music/main/install | bash
Cloning into 'Suda-Music'...
remote: Enumerating objects: 95, done.
remote: Counting objects: 100% (95/95), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 95 (delta 40), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (95/95), 39.77 MiB | 16.17 MiB/s, done.
Resolving deltas: 100% (40/40), done.
bash: line 4: cd: /home/pi/Suda-Music: No such file or directory
chmod: cannot access 'musicplayer.py': No such file or directory
chmod: cannot access 'start': No such file or directory
```

**Comment by Raspberry-Pi-Reviews** [comment]
is that the terminal output?

**Comment by Crilum** [comment]
Yeah

**Comment by Crilum** [comment]
While installing

**Comment by Raspberry-Pi-Reviews** [comment]
ok lemme check something

**Comment by Raspberry-Pi-Reviews** [comment]
do you have an idea whats wrong with the script?

**Comment by Crilum** [comment]
#2

**Comment by Crilum** [comment]
Actually, one sec, I wasn't in the home dir..

**Comment by Raspberry-Pi-Reviews** [comment]
ok

**Comment by Raspberry-Pi-Reviews** [comment]
im gonna open up a new "issue" but its gonna be named chat since you fixed the no sound issue

**Comment by Raspberry-Pi-Reviews** [comment]
im gonna close this one when you say something in the other issue thingy
