### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by Raspberry-Pi-Reviews** [Raspberry-Pi-Reviews/Suda-Music#3]
hello

**Comment by Crilum** [comment]
Hey

**Comment by Raspberry-Pi-Reviews** [comment]
ok ill go close the other one now

**Comment by Crilum** [comment]
You could enable Discussions if you want, so we're not just talking in an Issue.. :smile:

**Comment by Raspberry-Pi-Reviews** [comment]
oh lol ill do that

**Comment by Raspberry-Pi-Reviews** [comment]
done

**Comment by Raspberry-Pi-Reviews** [comment]
i forgot to say im gonna shut this down lol
